version: '3'
services:
  web:
    build: 
      network: host
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      #map files in current path to docker's "/app" folder
      - .:/app
  tests:
    build:
      network: host
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      #map files in current path to docker's "/app" folder
      - .:/app
    command: ["npm","run","test"]